#theme: jekyll-theme-slate
title: Amifa Raj
name: Amifa Raj
#logo: /images/
url: https://amprova.github.io/
collections:
  pubs:
    output: true
    permalink: /pubs/:year/:path
    sort_by:  date


defaults:
  - values:
      layout: single
  - scope:
      type: pubs
    values:
      layout: single


## Theming Configuration
remote_theme: mmistakes/minimal-mistakes@4.18.1
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache
